apiVersion: v1
kind: Service
metadata:
  name: active-mq-serive
  namespace: active-mq
  labels:
    app: active-mq
  namespace: dev-ns
spec:
  selector:
    app: active-mq
  ports:
  - name: dashboard
    port: 8161
    targetPort: 32445
    protocol: TCP
  - name: openwire
    port: 61616
    targetPort: 32117
    protocol: TCP
  - name: amqp
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: stomp
    port: 61613
    targetPort: 61613
    protocol: TCP
  - name: mqtt
    port: 1883
    targetPort: 1883
    protocol: TCP
  type: NodePort