apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-001
  labels:
    env: dev
  namespace: ns-dev-env
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi