apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-001
  labels:
     env: dev
  namespace: ns-dev-env
spec:
  capacity: 
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /srv/nfs/kubedata/db
    server: 172.16.1.99
  persistentVolumeReclaimPolicy: Recycle