apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-logging-elasticsearch-logging-0
  labels:
    env: dev
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi