apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-logging-pv
  labels:
     env: dev
  namespace: kube-system
spec:
  capacity: 
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /srv/nfs/kubedata/storage
    server: 172.16.1.99
  persistentVolumeReclaimPolicy: Recycle